// flow-typed signature: a62f1bac4316ba1856b962776eb04f24
// flow-typed version: <<STUB>>/client-sessions_v^0.8.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'client-sessions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'client-sessions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'client-sessions/lib/client-sessions' {
  declare module.exports: any;
}

declare module 'client-sessions/test/all-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'client-sessions/lib/client-sessions.js' {
  declare module.exports: $Exports<'client-sessions/lib/client-sessions'>;
}
declare module 'client-sessions/test/all-test.js' {
  declare module.exports: $Exports<'client-sessions/test/all-test'>;
}
