// flow-typed signature: d0e8e7271f137fd0993b9b407b7c8ce2
// flow-typed version: <<STUB>>/react-history_v^0.18.2/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-history'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-history' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-history/Actions' {
  declare module.exports: any;
}

declare module 'react-history/BrowserHistory' {
  declare module.exports: any;
}

declare module 'react-history/createHistoryComponent' {
  declare module.exports: any;
}

declare module 'react-history/createHistoryProvider' {
  declare module.exports: any;
}

declare module 'react-history/HashHistory' {
  declare module.exports: any;
}

declare module 'react-history/MemoryHistory' {
  declare module.exports: any;
}

declare module 'react-history/Prompt' {
  declare module.exports: any;
}

declare module 'react-history/PropTypes' {
  declare module.exports: any;
}

declare module 'react-history/umd/react-history' {
  declare module.exports: any;
}

declare module 'react-history/umd/react-history.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-history/Actions.js' {
  declare module.exports: $Exports<'react-history/Actions'>;
}
declare module 'react-history/BrowserHistory.js' {
  declare module.exports: $Exports<'react-history/BrowserHistory'>;
}
declare module 'react-history/createHistoryComponent.js' {
  declare module.exports: $Exports<'react-history/createHistoryComponent'>;
}
declare module 'react-history/createHistoryProvider.js' {
  declare module.exports: $Exports<'react-history/createHistoryProvider'>;
}
declare module 'react-history/HashHistory.js' {
  declare module.exports: $Exports<'react-history/HashHistory'>;
}
declare module 'react-history/index' {
  declare module.exports: $Exports<'react-history'>;
}
declare module 'react-history/index.js' {
  declare module.exports: $Exports<'react-history'>;
}
declare module 'react-history/MemoryHistory.js' {
  declare module.exports: $Exports<'react-history/MemoryHistory'>;
}
declare module 'react-history/Prompt.js' {
  declare module.exports: $Exports<'react-history/Prompt'>;
}
declare module 'react-history/PropTypes.js' {
  declare module.exports: $Exports<'react-history/PropTypes'>;
}
declare module 'react-history/umd/react-history.js' {
  declare module.exports: $Exports<'react-history/umd/react-history'>;
}
declare module 'react-history/umd/react-history.min.js' {
  declare module.exports: $Exports<'react-history/umd/react-history.min'>;
}
