// flow-typed signature: 58cede9efa2d352a6a28d6ba321867ae
// flow-typed version: <<STUB>>/react-notification-system-redux_v^1.2.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-notification-system-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-notification-system-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-notification-system-redux/dist/react-notification-system-redux' {
  declare module.exports: any;
}

declare module 'react-notification-system-redux/dist/react-notification-system-redux.min' {
  declare module.exports: any;
}

declare module 'react-notification-system-redux/example/src/components/container' {
  declare module.exports: any;
}

declare module 'react-notification-system-redux/example/src/example' {
  declare module.exports: any;
}

declare module 'react-notification-system-redux/example/src/store' {
  declare module.exports: any;
}

declare module 'react-notification-system-redux/gulpfile' {
  declare module.exports: any;
}

declare module 'react-notification-system-redux/lib/actions' {
  declare module.exports: any;
}

declare module 'react-notification-system-redux/lib/const' {
  declare module.exports: any;
}

declare module 'react-notification-system-redux/lib/notifications' {
  declare module.exports: any;
}

declare module 'react-notification-system-redux/lib/reducer' {
  declare module.exports: any;
}

declare module 'react-notification-system-redux/src/actions' {
  declare module.exports: any;
}

declare module 'react-notification-system-redux/src/const' {
  declare module.exports: any;
}

declare module 'react-notification-system-redux/src/notifications' {
  declare module.exports: any;
}

declare module 'react-notification-system-redux/src/reducer' {
  declare module.exports: any;
}

declare module 'react-notification-system-redux/test/__tests__/actions' {
  declare module.exports: any;
}

declare module 'react-notification-system-redux/test/__tests__/const' {
  declare module.exports: any;
}

declare module 'react-notification-system-redux/test/__tests__/notifications' {
  declare module.exports: any;
}

declare module 'react-notification-system-redux/test/__tests__/reducer' {
  declare module.exports: any;
}

declare module 'react-notification-system-redux/test/utils/dom' {
  declare module.exports: any;
}

declare module 'react-notification-system-redux/test/utils/enzyme' {
  declare module.exports: any;
}

declare module 'react-notification-system-redux/test/utils/rafPolyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-notification-system-redux/dist/react-notification-system-redux.js' {
  declare module.exports: $Exports<'react-notification-system-redux/dist/react-notification-system-redux'>;
}
declare module 'react-notification-system-redux/dist/react-notification-system-redux.min.js' {
  declare module.exports: $Exports<'react-notification-system-redux/dist/react-notification-system-redux.min'>;
}
declare module 'react-notification-system-redux/example/src/components/container.js' {
  declare module.exports: $Exports<'react-notification-system-redux/example/src/components/container'>;
}
declare module 'react-notification-system-redux/example/src/example.js' {
  declare module.exports: $Exports<'react-notification-system-redux/example/src/example'>;
}
declare module 'react-notification-system-redux/example/src/store.js' {
  declare module.exports: $Exports<'react-notification-system-redux/example/src/store'>;
}
declare module 'react-notification-system-redux/gulpfile.js' {
  declare module.exports: $Exports<'react-notification-system-redux/gulpfile'>;
}
declare module 'react-notification-system-redux/lib/actions.js' {
  declare module.exports: $Exports<'react-notification-system-redux/lib/actions'>;
}
declare module 'react-notification-system-redux/lib/const.js' {
  declare module.exports: $Exports<'react-notification-system-redux/lib/const'>;
}
declare module 'react-notification-system-redux/lib/notifications.js' {
  declare module.exports: $Exports<'react-notification-system-redux/lib/notifications'>;
}
declare module 'react-notification-system-redux/lib/reducer.js' {
  declare module.exports: $Exports<'react-notification-system-redux/lib/reducer'>;
}
declare module 'react-notification-system-redux/src/actions.js' {
  declare module.exports: $Exports<'react-notification-system-redux/src/actions'>;
}
declare module 'react-notification-system-redux/src/const.js' {
  declare module.exports: $Exports<'react-notification-system-redux/src/const'>;
}
declare module 'react-notification-system-redux/src/notifications.js' {
  declare module.exports: $Exports<'react-notification-system-redux/src/notifications'>;
}
declare module 'react-notification-system-redux/src/reducer.js' {
  declare module.exports: $Exports<'react-notification-system-redux/src/reducer'>;
}
declare module 'react-notification-system-redux/test/__tests__/actions.js' {
  declare module.exports: $Exports<'react-notification-system-redux/test/__tests__/actions'>;
}
declare module 'react-notification-system-redux/test/__tests__/const.js' {
  declare module.exports: $Exports<'react-notification-system-redux/test/__tests__/const'>;
}
declare module 'react-notification-system-redux/test/__tests__/notifications.js' {
  declare module.exports: $Exports<'react-notification-system-redux/test/__tests__/notifications'>;
}
declare module 'react-notification-system-redux/test/__tests__/reducer.js' {
  declare module.exports: $Exports<'react-notification-system-redux/test/__tests__/reducer'>;
}
declare module 'react-notification-system-redux/test/utils/dom.js' {
  declare module.exports: $Exports<'react-notification-system-redux/test/utils/dom'>;
}
declare module 'react-notification-system-redux/test/utils/enzyme.js' {
  declare module.exports: $Exports<'react-notification-system-redux/test/utils/enzyme'>;
}
declare module 'react-notification-system-redux/test/utils/rafPolyfill.js' {
  declare module.exports: $Exports<'react-notification-system-redux/test/utils/rafPolyfill'>;
}
