// flow-typed signature: caf5f72cac391c8835a6a38eafa1fbd6
// flow-typed version: <<STUB>>/redux-ui_v0.1.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-ui/src/action-reducer' {
  declare module.exports: any;
}

declare module 'redux-ui/src/index' {
  declare module.exports: any;
}

declare module 'redux-ui/src/ui' {
  declare module.exports: any;
}

declare module 'redux-ui/src/utils' {
  declare module.exports: any;
}

declare module 'redux-ui/test/action-reducer/reducer' {
  declare module.exports: any;
}

declare module 'redux-ui/test/setup' {
  declare module.exports: any;
}

declare module 'redux-ui/test/ui/context' {
  declare module.exports: any;
}

declare module 'redux-ui/test/ui/defaults' {
  declare module.exports: any;
}

declare module 'redux-ui/test/ui/key' {
  declare module.exports: any;
}

declare module 'redux-ui/test/ui/opts' {
  declare module.exports: any;
}

declare module 'redux-ui/test/ui/reducer' {
  declare module.exports: any;
}

declare module 'redux-ui/test/ui/reset' {
  declare module.exports: any;
}

declare module 'redux-ui/test/ui/validation' {
  declare module.exports: any;
}

declare module 'redux-ui/test/utils/render' {
  declare module.exports: any;
}

declare module 'redux-ui/transpiled/action-reducer' {
  declare module.exports: any;
}

declare module 'redux-ui/transpiled/index' {
  declare module.exports: any;
}

declare module 'redux-ui/transpiled/ui' {
  declare module.exports: any;
}

declare module 'redux-ui/transpiled/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-ui/src/action-reducer.js' {
  declare module.exports: $Exports<'redux-ui/src/action-reducer'>;
}
declare module 'redux-ui/src/index.js' {
  declare module.exports: $Exports<'redux-ui/src/index'>;
}
declare module 'redux-ui/src/ui.js' {
  declare module.exports: $Exports<'redux-ui/src/ui'>;
}
declare module 'redux-ui/src/utils.js' {
  declare module.exports: $Exports<'redux-ui/src/utils'>;
}
declare module 'redux-ui/test/action-reducer/reducer.js' {
  declare module.exports: $Exports<'redux-ui/test/action-reducer/reducer'>;
}
declare module 'redux-ui/test/setup.js' {
  declare module.exports: $Exports<'redux-ui/test/setup'>;
}
declare module 'redux-ui/test/ui/context.js' {
  declare module.exports: $Exports<'redux-ui/test/ui/context'>;
}
declare module 'redux-ui/test/ui/defaults.js' {
  declare module.exports: $Exports<'redux-ui/test/ui/defaults'>;
}
declare module 'redux-ui/test/ui/key.js' {
  declare module.exports: $Exports<'redux-ui/test/ui/key'>;
}
declare module 'redux-ui/test/ui/opts.js' {
  declare module.exports: $Exports<'redux-ui/test/ui/opts'>;
}
declare module 'redux-ui/test/ui/reducer.js' {
  declare module.exports: $Exports<'redux-ui/test/ui/reducer'>;
}
declare module 'redux-ui/test/ui/reset.js' {
  declare module.exports: $Exports<'redux-ui/test/ui/reset'>;
}
declare module 'redux-ui/test/ui/validation.js' {
  declare module.exports: $Exports<'redux-ui/test/ui/validation'>;
}
declare module 'redux-ui/test/utils/render.js' {
  declare module.exports: $Exports<'redux-ui/test/utils/render'>;
}
declare module 'redux-ui/transpiled/action-reducer.js' {
  declare module.exports: $Exports<'redux-ui/transpiled/action-reducer'>;
}
declare module 'redux-ui/transpiled/index.js' {
  declare module.exports: $Exports<'redux-ui/transpiled/index'>;
}
declare module 'redux-ui/transpiled/ui.js' {
  declare module.exports: $Exports<'redux-ui/transpiled/ui'>;
}
declare module 'redux-ui/transpiled/utils.js' {
  declare module.exports: $Exports<'redux-ui/transpiled/utils'>;
}
