// flow-typed signature: f4ce5390410fee2ebeec5965f59f4e79
// flow-typed version: <<STUB>>/superagent-promise_v^1.1.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'superagent-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'superagent-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'superagent-promise/browser_test' {
  declare module.exports: any;
}

declare module 'superagent-promise/index_test' {
  declare module.exports: any;
}

declare module 'superagent-promise/test/browser_test' {
  declare module.exports: any;
}

declare module 'superagent-promise/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'superagent-promise/browser_test.js' {
  declare module.exports: $Exports<'superagent-promise/browser_test'>;
}
declare module 'superagent-promise/index_test.js' {
  declare module.exports: $Exports<'superagent-promise/index_test'>;
}
declare module 'superagent-promise/index' {
  declare module.exports: $Exports<'superagent-promise'>;
}
declare module 'superagent-promise/index.js' {
  declare module.exports: $Exports<'superagent-promise'>;
}
declare module 'superagent-promise/test/browser_test.js' {
  declare module.exports: $Exports<'superagent-promise/test/browser_test'>;
}
declare module 'superagent-promise/test/index.js' {
  declare module.exports: $Exports<'superagent-promise/test/index'>;
}
