// flow-typed signature: 7121c87dbe0347db06dba03ca5ecee93
// flow-typed version: <<STUB>>/webpack-preset-babel_v^0.2.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-preset-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-preset-babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-preset-babel/index' {
  declare module.exports: $Exports<'webpack-preset-babel'>;
}
declare module 'webpack-preset-babel/index.js' {
  declare module.exports: $Exports<'webpack-preset-babel'>;
}
