// flow-typed signature: d2c5e3c96903aef2ff8cfc49a33752bb
// flow-typed version: <<STUB>>/webpack-preset_v^0.2.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-preset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-preset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-preset/bin/webpack-preset' {
  declare module.exports: any;
}

declare module 'webpack-preset/src/config/base' {
  declare module.exports: any;
}

declare module 'webpack-preset/src/config/index' {
  declare module.exports: any;
}

declare module 'webpack-preset/src/config/json' {
  declare module.exports: any;
}

declare module 'webpack-preset/src/config/presets' {
  declare module.exports: any;
}

declare module 'webpack-preset/src/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-preset/bin/webpack-preset.js' {
  declare module.exports: $Exports<'webpack-preset/bin/webpack-preset'>;
}
declare module 'webpack-preset/src/config/base.js' {
  declare module.exports: $Exports<'webpack-preset/src/config/base'>;
}
declare module 'webpack-preset/src/config/index.js' {
  declare module.exports: $Exports<'webpack-preset/src/config/index'>;
}
declare module 'webpack-preset/src/config/json.js' {
  declare module.exports: $Exports<'webpack-preset/src/config/json'>;
}
declare module 'webpack-preset/src/config/presets.js' {
  declare module.exports: $Exports<'webpack-preset/src/config/presets'>;
}
declare module 'webpack-preset/src/server.js' {
  declare module.exports: $Exports<'webpack-preset/src/server'>;
}
