// @flow

// 1. --- account

// auth
export const SHOW_LOGIN_CAPTCHA = "SHOW_LOGIN_CAPTCHA";
export const HIDE_LOGIN_CAPTCHA = "HIDE_LOGIN_CAPTCHA";

// info
export const FETCH_CURRENT_ACCOUNT = "FETCH_CURRENT_ACCOUNT";
export const ACCOUNT_CHANGE_PASSWORD = "ACCOUNT_CHANGE_PASSWORD";

// suggestions
export const FETCH_SUGGESTIONS = "FETCH_SUGGESTIONS";
export const CHANGE_SUGGESTIONS_CURRENT_TERM = "CHANGE_SUGGESTIONS_CURRENT_TERM";

// notifications
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";

// modal
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

// bankHoliday
export const FETCH_BANK_HOLIDAYS = "FETCH_BANK_HOLIDAYS";
export const ADD_BANK_HOLIDAY = "ADD_BANK_HOLIDAY";
export const MODIFY_BANK_HOLIDAY = "MODIFY_BANK_HOLIDAY";
export const DELETE_BANK_HOLIDAY = "DELETE_BANK_HOLIDAY";
export const LOAD_BANK_HOLIDAYS = "LOAD_BANK_HOLIDAYS";

// company
export const FETCH_COMPANIES = "FETCH_COMPANIES";
export const ADD_COMPANY = "ADD_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const SET_INACTIVE_COMPANY = "SET_INACTIVE_COMPANY";

// accounts
export const FETCH_ACCOUNTS = "FETCH_ACCOUNTS";
export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const MODAL_MODIFY_ACCOUNT = "MODAL_MODIFY_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const SET_INACTIVE_ACCOUNT = "SET_INACTIVE_ACCOUNT";
export const RESET_PASSWORD_ACCOUNT = "RESET_PASSWORD_ACCOUNT";

// 2. --- company

// info
export const FETCH_CURRENT_COMPANY_INFO = "FETCH_CURRENT_COMPANY_INFO";
export const MODIFY_CURRENT_COMPANY_INFO = "MODIFY_CURRENT_COMPANY_INFO";

// article
export const COMPANY_FETCH_ARTICLES = "COMPANY_FETCH_ARTICLES";
export const COMPANY_ADD_ARTICLE = "COMPANY_ADD_ARTICLE";
export const COMPANY_MODIFY_ARTICLE = "COMPANY_MODIFY_ARTICLE";
export const COMPANY_DELETE_ARTICLE = "COMPANY_DELETE_ARTICLE";

// permission
export const COMPANY_FETCH_PERMISSIONS = "COMPANY_FETCH_PERMISSIONS";
export const COMPANY_ADD_PERMISSION = "COMPANY_ADD_PERMISSION";
export const COMPANY_MODIFY_PERMISSION = "COMPANY_MODIFY_PERMISSION";
export const COMPANY_DELETE_PERMISSION = "COMPANY_DELETE_PERMISSION";

// client
export const COMPANY_FETCH_CLIENTS = "COMPANY_FETCH_CLIENTS";
export const COMPANY_ADD_CLIENT = "COMPANY_ADD_CLIENT";
export const COMPANY_MODIFY_CLIENT = "COMPANY_MODIFY_CLIENT";
export const COMPANY_DELETE_CLIENT = "COMPANY_DELETE_CLIENT";

// employee
export const COMPANY_FETCH_EMPLOYEES = "COMPANY_FETCH_EMPLOYEES";
export const COMPANY_ADD_EMPLOYEE = "COMPANY_ADD_EMPLOYEE";
export const COMPANY_MODIFY_EMPLOYEE = "COMPANY_MODIFY_EMPLOYEE";
export const COMPANY_DELETE_EMPLOYEE = "COMPANY_DELETE_EMPLOYEE";
export const COMPANY_LOAD_EMPLOYEES = "COMPANY_LOAD_EMPLOYEES";

// delegate
export const COMPANY_FETCH_DELEGATES = "COMPANY_FETCH_DELEGATES";
export const COMPANY_ADD_DELEGATE = "COMPANY_ADD_DELEGATE";
export const COMPANY_MODIFY_DELEGATE = "COMPANY_MODIFY_DELEGATE";
export const COMPANY_DELETE_DELEGATE = "COMPANY_DELETE_DELEGATE";

// serial
export const COMPANY_FETCH_SERIALS = "COMPANY_FETCH_SERIALS";
export const COMPANY_ADD_SERIAL = "COMPANY_ADD_SERIAL";
export const COMPANY_MODIFY_SERIAL = "COMPANY_MODIFY_SERIAL";
export const COMPANY_DELETE_SERIAL = "COMPANY_DELETE_SERIAL";

// invoice
export const COMPANY_FETCH_INVOICES = "COMPANY_FETCH_INVOICES";
export const COMPANY_FETCH_INVOICES_BY_CLIENT = "COMPANY_FETCH_INVOICES_BY_CLIENT";
export const COMPANY_ADD_INVOICE = "COMPANY_ADD_INVOICE";
export const COMPANY_DELETE_INVOICE = "COMPANY_DELETE_INVOICE";
export const COMPANY_FETCH_INVOICE = "COMPANY_FETCH_INVOICE";

// cashings
export const COMPANY_ADD_CASHING = "COMPANY_ADD_CASHING";
export const COMPANY_MODIFY_CASHING = "COMPANY_MODIFY_CASHING";
export const COMPANY_DELETE_CASHING = "COMPANY_DELETE_CASHING";

// others
export const COMPANY_RESET_DATA = `${FETCH_CURRENT_COMPANY_INFO}_PENDING`;
